#peter keres
#3-1-2020

# simple make file that complies and loads the example 1 program for kotlin

all:
	@clear
	@echo '*********** LOADING KOTLIN EXAMPLE 1 **************'
	@kotlinc number_guessing.kt -include-runtime -d number_guessing.jar
	@clear
	@java -jar number_guessing.jar